language: node_js
node_js: v12.11.1
branches:
  except:
    - develop
  only:
    - master
env:
  - project=webui
before_install:
  - echo 'before install'
  - echo `pwd`
install:
  - echo 'install'
before_script:
  - echo "before script"
script:
  - echo "script"
