language: node_js
node_js: v12.11.1
cache:
  directories:
    - node_modules
branches:
  except:
    - develop
  only:
    - master
env:
  - project=webui

jobs:
include:
  - stage: build
    before_install:
      - npm i gulp-cli -g
      - npm i
    script:
      - echo "script"
      - gulp html
      - ls
      - tar zcvf travis.tar.gz -C dist
  - stage: test
    script: echo "test"
  - stage: deploy
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      file: dist/*.tar.gz
      skip_cleanup: true
      on:
        tags: false
