language: node_js
node_js: v12.11.1
branches:
  except:
    - develop
  only:
    - master
env:
  - project=webui
before_install:
  - echo 'before install'
  - echo `pwd`
install:
  - echo 'install'
before_script:
  - echo "before script"
script:
  - echo "script"
after_success:
  - echo "project is $project"
deploy:
  - echo "deploy"
after_deploy:
  - echo 'after deploy'
after_script:
  - echo "version is $version"
